# Generated by Django 5.1 on 2024-06-28 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.UUID('d5a5dad2-d9b1-48e8-9a7b-44758349188d'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(editable=False, max_length=255)),
                ('course_created_by', models.CharField(max_length=255)),
                ('course_created_date', models.DateTimeField(auto_now_add=True)),
                ('course_updated_by', models.CharField(max_length=255, null=True)),
                ('course_updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('course_id',),
                'indexes': [models.Index(fields=['course_id'], name='webpem_cour_course__9a1523_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('account_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_user_fullname', models.CharField(editable=False, max_length=255)),
                ('account_user_student_number', models.CharField(max_length=20)),
                ('account_user_created_by', models.CharField(max_length=255)),
                ('account_user_created_date', models.DateTimeField(auto_now_add=True)),
                ('account_user_updated_by', models.CharField(max_length=255, null=True)),
                ('account_user_updated_date', models.DateTimeField(auto_now=True)),
                ('account_user_related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('account_user_related_user',),
                'indexes': [models.Index(fields=['account_user_id', 'account_user_related_user'], name='webpem_acco_account_9e91ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendingCourse',
            fields=[
                ('attending_course_id', models.UUIDField(default=uuid.UUID('202f70b0-65ad-4dfa-b753-e7ee67145faf'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('attending_account_profile_id', models.CharField(editable=False, max_length=255)),
                ('attending_course_created_by', models.CharField(max_length=255)),
                ('attending_course_created_date', models.DateTimeField(auto_now_add=True)),
                ('attending_course_updated_by', models.CharField(max_length=255, null=True)),
                ('attending_course_updated_date', models.DateTimeField(auto_now_add=True)),
                ('attending_courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpem.course')),
            ],
            options={
                'ordering': ('attending_course_id',),
                'indexes': [models.Index(fields=['attending_course_id', 'attending_courseid'], name='webpem_atte_attendi_1980b7_idx')],
            },
        ),
    ]
