# Generated by Django 5.0.4 on 2024-07-07 02:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('326906fe-1fda-425d-8680-dd17efc97fdc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('53d7a758-236a-4d72-8e4d-fd3015355e02'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
