# Generated by Django 5.0.4 on 2024-07-07 03:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpem', '0003_rename_webpem_acco_account_9e91ba_idx_webpem_acco_account_c29ec3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('5350eb61-722a-4c56-9bab-3b751a6b79a2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('cc44671e-d339-4b64-91aa-381f69f34882'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
