# Generated by Django 5.0.4 on 2024-07-07 03:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpem', '0004_alter_attendingcourse_attending_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('4068086e-1f76-4ba6-a78a-561e55d571ac'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('43fb85ac-567d-4e31-aaf0-d8289ce8cc20'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
